# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-rootheater

# >> macros
# << macros

Summary:    RooTheater is a multimedia player for Sailfish OS
Version:    0.9.5
Release:    1
Group:      Qt/Qt
License:    GPL-3.0
URL:        https://github.com/RootGPT-YouTube/RooTheater-SailfishOS
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-rootheater.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   nemo-qml-plugin-configuration-qt5
Requires:   sailfish-components-webview-qt5
Requires:   qt5-plugin-sqldriver-sqlite
Requires:   grilo-qt5-qml-plugin
Requires:   grilo-plugin-tracker
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  desktop-file-utils

%description
RooTheater is a multimedia player for Sailfish OS, focused on
hardware-accelerated playback of local files and network streams.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
